import datetime  # for footer timestamp
import os


def write_executive_summary(output_path, summary, recommendations):
    """Write formatted executive summary to file."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    # Create the 1-paragraph description
    if summary["health_status"] == "RED":
        description = f"Backup operations are in a critical state with {summary['error_count']} failures out of {summary['total_backups']} jobs. Immediate intervention is required to restore data protection."
    elif summary["health_status"] in ["AMBER", "YELLOW"]:
        description = f"Backup operations have warnings. {summary['successful_backups']} of {summary['total_backups']} jobs succeeded. Monitoring is advised."
    else:
        description = f"All backup operations completed successfully. {summary['successful_backups']} of {summary['total_backups']} jobs passed with no issues."

    lines = []
    lines.append("=" * 50)
    lines.append(" EXECUTIVE SUMMARY - BACKUP HEALTH")
    lines.append("=" * 50)
    lines.append(f"Report Date: {summary['report_date']}")
    lines.append("")
    lines.append("--- Overview ---")
    lines.append(description)
    lines.append("")
    lines.append("--- Key Metrics ---")
    lines.append(f" Total Backups: {summary['total_backups']}")
    lines.append(f" Successful: {summary['successful_backups']}")
    lines.append(f" Errors: {summary['error_count']}")
    lines.append(f" Status: {summary['health_status']}")
    lines.append("")
    lines.append("--- Recommendations ---")
    for i, rec in enumerate(recommendations, 1):
        lines.append(f" {i}. {rec}")
    lines.append("")
    lines.append("-" * 50)
    lines.append(f"Generated by: executive_summary.py")
    lines.append(
        f"Generated at: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"SUCCESS: Executive summary written to {output_path}")


def read_and_parse_report(report_path):
    """Read daily_report.txt and extract key values."""
    try:
        with open(report_path, "r") as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"ERROR:Report file not found at {report_path}")
        return None  # stop if file missing

    report_date = ""
    status = ""
    success = 0
    warnings = 0
    errors = 0

    for line in lines:
        if "Date :" in line:
            report_date = line.split(":")[1].strip()
        elif "Status:" in line:
            status = line.split(":")[1].strip()
        elif "Successful backups:" in line:
            success = int(line.split(":")[1].strip())
        elif "Warnings:" in line:
            warning = int(line.split(":")[1].strip())
        elif "Errors:" in line:
            errors = int(line.split(":")[1].strip())

    total = success + warnings + errors
    return report_date, total, success, errors, status


def build_summary(date, total, success, errors, status):
    """Build dictionay and recommendation list."""
    summary = {
        "report_date": date,
        "total_backups": total,
        "successful_backups": success,
        "error_count": errors,
        "health_status": status,
    }

    recommendations = []
    if status == "RED":
        recommendations.append("Escalate to an on-call engineer immediately.")
        recommendations.append("Review failed backup logs and re-run critical jobs.")
    elif status == "AMBER" or status == "YELLOW":
        recommendations.append("Monitor backup jobs closely over the next 24 hours.")
    else:
        recommendations.append("Backup health is optimal. No action required.")

    return summary, recommendations


def main():
    REPORT_INPUT = "interswitch_backups/daily_report.txt"
    SUMMARY_OUTPUT = "interswitch_backups/executive_summary.txt"

    # Part A
    parsed_data = read_and_parse_report(REPORT_INPUT)
    if parsed_data is None:
        return  # exit if file not found

    date, total, success, errors, status = parsed_data

    # Part B
    summary_dict, rec_list = build_summary(date, total, success, errors, status)

    # Part C
    write_executive_summary(SUMMARY_OUTPUT, summary_dict, rec_list)


if __name__ == "__main__":
    main()
